### ISSUE TITLE
Prometheus data source enhancement 

### ISSUE THREAD

**Issue by marcpawl** [Vonage/Grafana_Status_panel#64] opened 2017-06-18 21:57 UTC
Tried to use the plugin with prometheus even though I knew it was not supported.   Please addsupport for prometheus to you plans

**Comment by benjaminguttmann-avtq** [comment] 2017-06-20 08:23
Hey, perhaps #17 would help you?

**Comment by TomerAmirV** [comment] 2017-06-20 08:27
Hi @marcpawl,

@benjaminguttmann-avtq is right. this is a duplicate of #17.

Currently, we are working on other things, so I can't say when we will get to add this support, but you are welcome to do it and make a pull request. I can help with any questions you might have.

Thanks!

**Closed** 2017-06-20 08:28 UTC
Labels: duplicate
