### ISSUE TITLE
Support for Grafana 4.x

### ISSUE THREAD

**Issue by paulcgt** [Vonage/Grafana_Status_panel#13] opened 2017-01-20 08:25 UTC
It looks like Grafana Status Panel isn't working with Grafana 4.1.x. Do you have plans to support Grafana 4.x?

It seems I can't configure Grafana Status Panel in 4.1.1 because I'm not able to define thresholds on the Options tab.

**Comment by TomerAmirV** [comment] 2017-01-22 08:28
Hello @paulcgt ,

Which type of data source are you trying to use with it?
Currently, we have support for InfluxDB, but I am trying to find time to add support for Graphite.

**Comment by paulcgt** [comment] 2017-01-22 20:25
Hey @TomerAmirV , 

Yeah, that's it then. I'm using Graphite as my source. 

I don't have time right now to help out with the change, but if you haven't included support for Graphite by the time I do have time then I'll see if I can implement it.

Thanks for getting back to me.

**Comment by TomerAmirV** [comment] 2017-01-23 08:22
Duplicate of issue #5 

You're welcome to fork us and make a pull request 😄

**Closed by TomerAmirV** 2017-01-23 08:22 UTC
Labels: duplicate
